
server:
  port: 8080
  servlet:
    context-path: /musify

musify:
  client:
    music-brainz:
      artist-url: http://musicbrainz.org/ws/2/artist/%s?fmt=json&inc=url-rels+release-groups
      user-agent-header: MusicService (earosselot@gmail.com)
      connect-timeout-ms: 2000
      read-timeout-ms: 2000
    wikidata:
      entity-data-url: https://www.wikidata.org/wiki/Special:EntityData/%s.json
      connect-timeout-ms: 2000
      read-timeout-ms: 2000
    wikipedia:
      summary-url: https://en.wikipedia.org/api/rest_v1/page/summary/%s
      connect-timeout-ms: 2000
      read-timeout-ms: 2000
    cover-art-archive:
      cover-url: http://coverartarchive.org/release-group/%s
      connect-timeout-ms: 2000
      read-timeout-ms: 2000

---
spring:
  config:
    activate:
      on-profile: prod

server:
  error:
    include-stacktrace: never

springdoc.swagger-ui.enabled: false